// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Properties that can be animated
 */
export type AnimatableProperty = { "Opacity": number } | { "Fill": string } | { "Stroke": string } | { "StrokeWidth": number } | { "Transform": string } | { "Translate": [number, number] } | { "Rotate": number } | { "Scale": [number, number] } | { "PathD": string } | { "X": number } | { "Y": number } | { "Cx": number } | { "Cy": number } | { "R": number } | { "Width": number } | { "Height": number };
