// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Animation } from "./Animation";
import type { Transition } from "./Transition";

/**
 * Animation state attached to a shape
 */
export type AnimationState = { 
/**
 * Animation (references keyframes)
 */
animation: Animation | null, 
/**
 * Transitions for property changes
 */
transitions: Array<Transition>, };
