// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";
import type { Duration } from "./Duration";
import type { Easing } from "./Easing";
import type { FillMode } from "./FillMode";
import type { Iteration } from "./Iteration";
import type { PlayState } from "./PlayState";

/**
 * Animation applied to an element (references a Keyframes definition)
 */
export type Animation = { 
/**
 * Name of @keyframes to use
 */
name: string, 
/**
 * Duration
 */
duration: Duration, 
/**
 * Timing function
 */
easing: Easing, 
/**
 * Delay before start
 */
delay: Duration, 
/**
 * Number of iterations
 */
iteration: Iteration, 
/**
 * Playback direction
 */
direction: Direction, 
/**
 * Fill mode
 */
fill_mode: FillMode, 
/**
 * Play state
 */
play_state: PlayState, };
