// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Arrow type enumeration
 */
export type ArrowType = "None" | "Forward" | "Backward" | "Both";
