// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasSize } from "./CanvasSize";

/**
 * Canvas definition using standardized sizes
 */
export type AstCanvas = { size: CanvasSize, fill: string, };
