// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphEdge } from "./GraphEdge";
import type { GraphNode } from "./GraphNode";

/**
 * Graph container with layout
 */
export type AstGraph = { layout: string, direction: string, spacing: number, nodes: Array<GraphNode>, edges: Array<GraphEdge>, };
