// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AstCanvas } from "./AstCanvas";
import type { AstGraph } from "./AstGraph";
import type { AstShape } from "./AstShape";
import type { TokenValue } from "./TokenValue";

/**
 * AST node types
 */
export type AstNode = { "Scene": Array<AstNode> } | { "Canvas": AstCanvas } | { "Shape": AstShape } | { "Graph": AstGraph } | { "Variable": { name: string, value: TokenValue | null, } };
