// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Style properties for shapes
 */
export type AstStyle = { fill: string | null, stroke: string | null, stroke_width: number, opacity: number, corner: number, font: string | null, font_size: number, font_weight: string, text_anchor: string, };
