// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AstStyle } from "./AstStyle";
import type { AstTransform } from "./AstTransform";
import type { GradientDef } from "./GradientDef";
import type { PropValue } from "./PropValue";
import type { ShadowDef } from "./ShadowDef";

/**
 * Shape in the AST
 */
export type AstShape = { kind: string, props: { [key in string]?: PropValue }, style: AstStyle, shadow: ShadowDef | null, gradient: GradientDef | null, transform: AstTransform, children: Array<AstShape>, };
