// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AstShape } from "./AstShape";

/**
 * Symbol definition for reusable components (SVG <symbol>)
 */
export type AstSymbol = { id: string, viewbox: [number, number, number, number] | null, children: Array<AstShape>, };
