// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transform properties
 */
export type AstTransform = { translate: [number, number] | null, rotate: number, scale: [number, number] | null, origin: [number, number] | null, };
