// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AstStyle } from "./AstStyle";
import type { AstTransform } from "./AstTransform";

/**
 * Use reference for symbol instances (SVG <use>)
 */
export type AstUse = { href: string, at: [number, number] | null, size: [number, number] | null, transform: AstTransform, style: AstStyle, };
