// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Standard canvas sizes (10-tier system)
 */
export type CanvasSize = "Nano" | "Micro" | "Tiny" | "Small" | "Medium" | "Large" | "XLarge" | "Huge" | "Massive" | "Giant";
