// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeStyle } from "./ShapeStyle";

/**
 * Circle primitive
 */
export type Circle = { cx: number, cy: number, r: number, style: ShapeStyle, transform: string | null, };
