// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Axis } from "./Axis";
import type { Dimension } from "./Dimension";
import type { Edge } from "./Edge";

/**
 * Layout constraint for constraint-based positioning
 */
export type Constraint = { "AnchorEdge": { edge: Edge, offset: Dimension, } } | { "CenterAxis": { axis: Axis, offset: Dimension, } } | { "MatchSize": { target: string, axis: Axis, } } | { "Fill": { weight: number, } };
