// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeStyle } from "./ShapeStyle";

/**
 * Diamond primitive (rotated rect for flowcharts)
 */
export type Diamond = { cx: number, cy: number, w: number, h: number, style: ShapeStyle, transform: string | null, };
