// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dimension value type for flexible sizing
 */
export type Dimension = { "Px": number } | { "Percent": number } | "Auto";
