// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dimension } from "./Dimension";

/**
 * Dimension pair for width/height
 */
export type DimensionPair = { width: Dimension, height: Dimension, };
