// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Animation playback direction
 */
export type Direction = "Normal" | "Reverse" | "Alternate" | "AlternateReverse";
