// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Duration in milliseconds (internal representation)
 */
export type Duration = number;
