// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepPosition } from "./StepPosition";

/**
 * Timing function for animations/transitions
 */
export type Easing = "Linear" | "Ease" | "EaseIn" | "EaseOut" | "EaseInOut" | { "CubicBezier": [number, number, number, number] } | { "Steps": [number, StepPosition] };
