// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Edge style enumeration
 */
export type EdgeStyle = "Straight" | "Curved" | "Orthogonal";
