// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Edge for constraint anchoring
 */
export type Edge = "Top" | "Right" | "Bottom" | "Left";
