// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Circle } from "./Circle";
import type { Diamond } from "./Diamond";
import type { Edge } from "./Edge";
import type { Ellipse } from "./Ellipse";
import type { GraphContainer } from "./GraphContainer";
import type { GraphNodeShape } from "./GraphNodeShape";
import type { ImageShape } from "./ImageShape";
import type { Line } from "./Line";
import type { Path } from "./Path";
import type { Polygon } from "./Polygon";
import type { Rect } from "./Rect";
import type { TextShape } from "./TextShape";
import type { Use } from "./Use";

/**
 * A renderable element in the scene
 */
export type Element = { "Rect": Rect } | { "Circle": Circle } | { "Ellipse": Ellipse } | { "Line": Line } | { "Path": Path } | { "Polygon": Polygon } | { "Text": TextShape } | { "Image": ImageShape } | { "Diamond": Diamond } | { "Node": GraphNodeShape } | { "Edge": Edge } | { "Group": [Array<Element>, string | null] } | { "Graph": GraphContainer } | { "Use": Use };
