// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeStyle } from "./ShapeStyle";

/**
 * Ellipse primitive
 */
export type Ellipse = { cx: number, cy: number, rx: number, ry: number, style: ShapeStyle, transform: string | null, };
