// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error categories for structured diagnostics
 */
export type ErrorKind = "UnexpectedToken" | "UnknownCommand" | "InvalidValue" | "MissingToken" | "InvalidIndentation" | "UnterminatedBlock" | "InvalidProperty" | "UndefinedVariable" | "DuplicateVariable";
