// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Animation fill mode (how styles apply before/after)
 */
export type FillMode = "None" | "Forwards" | "Backwards" | "Both";
