// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter definition
 */
export type Filter = { id: string, kind: string, dx: number, dy: number, blur: number, color: string, };
