// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AstStyle } from "./AstStyle";
import type { GradientDef } from "./GradientDef";
import type { ShadowDef } from "./ShadowDef";

/**
 * Extended style with shadow/gradient (separate for Python compat)
 */
export type FullStyle = { base: AstStyle, shadow: ShadowDef | null, gradient: GradientDef | null, };
