// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Gradient definition
 */
export type GradientShape = { id: string, kind: string, from_color: string, to_color: string, angle: number, };
