// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Gradient definition
 */
export type GradientDef = { gtype: string, from: string, to: string, angle: number, };
