// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edge } from "./Edge";
import type { GraphNodeShape } from "./GraphNodeShape";

/**
 * Container for graph elements with layout info
 */
export type GraphContainer = { layout: string, direction: string, spacing: number, nodes: Array<GraphNodeShape>, edges: Array<Edge>, };
