// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeStyle } from "./ShapeStyle";

/**
 * Node for graph/flowchart (composite: shape + label)
 */
export type GraphNodeShape = { id: string, shape: string, cx: number, cy: number, w: number, h: number, label: string | null, style: ShapeStyle, label_style: ShapeStyle, transform: string | null, };
