// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Edge/connector between nodes
 */
export type GraphEdge = { from: string, to: string, style: string, arrow: string, label: string | null, stroke: string | null, stroke_width: number, };
