// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AstStyle } from "./AstStyle";

/**
 * Node definition for graphs/flowcharts
 */
export type GraphNode = { id: string, shape: string, label: string | null, at: [number, number] | null, size: [number, number] | null, style: AstStyle, };
