// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Image primitive
 */
export type ImageShape = { x: number, y: number, w: number, h: number, href: string, transform: string | null, };
