// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Easing } from "./Easing";

/**
 * Temporal interpolation for frame-based animation
 * Used for programmatic animation control (e.g., in real-time updates)
 */
export type Interpolation = { 
/**
 * Start time (ms from animation start)
 */
start: number, 
/**
 * End time (ms)
 */
end: number, 
/**
 * From value
 */
from: number, 
/**
 * To value  
 */
to: number, 
/**
 * Easing function
 */
easing: Easing, };
