// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Number of animation iterations
 */
export type Iteration = { "Count": number } | "Infinite";
