// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyframeStep } from "./KeyframeStep";

/**
 * Named keyframes animation definition (CSS @keyframes)
 */
export type Keyframes = { name: string, steps: Array<KeyframeStep>, };
