// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimatableProperty } from "./AnimatableProperty";

/**
 * Single keyframe in an animation sequence
 */
export type KeyframeStep = { 
/**
 * Offset within animation (0-100%)
 */
offset: number, 
/**
 * Style properties to animate
 */
properties: Array<AnimatableProperty>, };
