// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlignItems } from "./AlignItems";
import type { Constraint } from "./Constraint";
import type { Dimension } from "./Dimension";
import type { JustifyContent } from "./JustifyContent";

/**
 * Layout properties for containers
 */
export type LayoutProps = { direction: string | null, justify: JustifyContent, align: AlignItems, gap: Dimension, padding: [Dimension, Dimension, Dimension, Dimension] | null, wrap: boolean, constraints: Array<Constraint>, };
