// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeStyle } from "./ShapeStyle";

/**
 * Line primitive
 */
export type Line = { x1: number, y1: number, x2: number, y2: number, style: ShapeStyle, transform: string | null, };
