// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";
import type { ErrorSeverity } from "./ErrorSeverity";
import type { Span } from "./Span";

/**
 * Parse error with recovery context
 */
export type ParseError = { message: string, line: number, col: number, kind: ErrorKind, severity: ErrorSeverity, span: Span, suggestion: string | null, recovered: boolean, };
