// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeStyle } from "./ShapeStyle";

/**
 * Path primitive
 */
export type Path = { d: string, style: ShapeStyle, transform: string | null, bounds_hint: [number, number, number, number] | null, };
