// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeStyle } from "./ShapeStyle";

/**
 * Polygon primitive
 */
export type Polygon = { points: Array<[number, number]>, style: ShapeStyle, transform: string | null, };
