// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dimension } from "./Dimension";
import type { DimensionPair } from "./DimensionPair";
import type { LayoutProps } from "./LayoutProps";

/**
 * Property value types
 */
export type PropValue = "None" | { "Str": string } | { "Num": number } | { "Pair": [number, number] } | { "Points": Array<[number, number]> } | { "Dim": Dimension } | { "DimPair": DimensionPair } | { "PercentPair": [number, number] } | { "Layout": LayoutProps } | { "VarRef": [string, number, number] };
