// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeStyle } from "./ShapeStyle";

/**
 * Rectangle primitive
 */
export type Rect = { x: number, y: number, w: number, h: number, rx: number, style: ShapeStyle, transform: string | null, };
