// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CSS keyframes animation definition
 */
export type SceneKeyframes = { name: string, css: string, };
