// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shadow definition
 */
export type ShadowDef = { x: number, y: number, blur: number, color: string, };
