// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Style properties for shapes
 */
export type ShapeStyle = { fill: string | null, stroke: string | null, stroke_width: number, opacity: number, corner: number, filter: string | null, 
/**
 * Animation class name (references CSS animation)
 */
animation_class: string | null, };
