// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeStyle } from "./ShapeStyle";

/**
 * Text primitive
 */
export type TextShape = { x: number, y: number, content: string, font: string, size: number, weight: string, anchor: string, style: ShapeStyle, transform: string | null, };
