// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenType } from "./TokenType";
import type { TokenValue } from "./TokenValue";

/**
 * A single token from the lexer
 */
export type Token = { ttype: TokenType, value: TokenValue, line: number, col: number, };
