// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token types for lexical analysis
 */
export type TokenType = "Ident" | "Number" | "Percent" | "String" | "Color" | "Var" | "Pair" | "PercentPair" | "Size" | "Colon" | "Equals" | "Arrow" | "LBracket" | "RBracket" | "Newline" | "Indent" | "Dedent" | "Eof" | "AtKeyframes" | "Duration";
