// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token value variants
 */
export type TokenValue = "None" | { "Str": string } | { "Num": number } | { "Pair": [number, number] } | { "PercentPair": [number, number] };
