// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Duration } from "./Duration";
import type { Easing } from "./Easing";

/**
 * CSS transition for property changes
 */
export type Transition = { 
/**
 * Property to transition ("all" for any)
 */
property: string, 
/**
 * Duration
 */
duration: Duration, 
/**
 * Timing function
 */
easing: Easing, 
/**
 * Delay before transition starts
 */
delay: Duration, };
