// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeStyle } from "./ShapeStyle";

/**
 * Use reference to instantiate a symbol (SVG <use>)
 */
export type Use = { href: string, x: number, y: number, width: number | null, height: number | null, style: ShapeStyle, transform: string | null, };
