//! TypeScript type export module
//!
//! Run `cargo test export_ts_bindings -- --ignored` to generate TypeScript bindings.

#[cfg(test)]
mod tests {
    use std::fs;
    
    /// Export all TypeScript bindings to the npm distribution folder.
    /// Run with: `cargo test export_ts_bindings -- --ignored`
    #[test]
    #[ignore]
    fn export_ts_bindings() {
        use ts_rs::TS;
        
        // Use public re-exports from crate root
        use crate::{
            // Lexer types
            CanvasSize, Token, TokenType, TokenValue,
            // AST types
            AstCanvas, AstGraph, AstNode, AstShape, AstStyle, AstTransform,
            ErrorKind, ErrorSeverity, FullStyle, GradientDef, GraphEdge, GraphNode,
            ParseError, PropValue, ShadowDef, Span,
            // Scene types (Path renamed to avoid conflict with std::path::Path)
            ArrowType, Circle, Color, Diamond, Edge, EdgeStyle, Element, Ellipse,
            Filter, Gradient, GraphContainer, Image, Line, Node, Path as ShapePath, Polygon,
            Rect, Style, Text,
        };
        
        let out_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../distribution/npm/src/core/generated");
        
        fs::create_dir_all(&out_dir).expect("Failed to create output directory");
        
        // Macro to get type definition and strip ts-rs comments
        macro_rules! get_type_def {
            ($t:ty) => {
                match <$t>::export_to_string() {
                    Ok(s) => s.lines()
                        .filter(|l| !l.starts_with("// This file was generated"))
                        .filter(|l| !l.starts_with("import type"))
                        .collect::<Vec<_>>()
                        .join("\n")
                        .trim()
                        .to_string(),
                    Err(e) => {
                        eprintln!("Failed to export {}: {}", stringify!($t), e);
                        String::new()
                    }
                }
            };
        }

        // Build output with organized sections
        let mut output = String::from(
r#"// ═══════════════════════════════════════════════════════════════════════════
// GENERATED BY ts-rs - DO NOT EDIT
// Run `cargo test export_ts_bindings -- --ignored` in source/core to regenerate
// ═══════════════════════════════════════════════════════════════════════════

// ─────────────────────────────────────────────────────────────────────────────
// Lexer Types
// ─────────────────────────────────────────────────────────────────────────────

"#);
        output.push_str(&get_type_def!(TokenType)); output.push_str("\n\n");
        output.push_str(&get_type_def!(CanvasSize)); output.push_str("\n\n");
        output.push_str(&get_type_def!(TokenValue)); output.push_str("\n\n");
        output.push_str(&get_type_def!(Token)); output.push_str("\n\n");

        output.push_str(r#"// ─────────────────────────────────────────────────────────────────────────────
// AST Types
// ─────────────────────────────────────────────────────────────────────────────

"#);
        output.push_str(&get_type_def!(AstStyle)); output.push_str("\n\n");
        output.push_str(&get_type_def!(ShadowDef)); output.push_str("\n\n");
        output.push_str(&get_type_def!(GradientDef)); output.push_str("\n\n");
        output.push_str(&get_type_def!(FullStyle)); output.push_str("\n\n");
        output.push_str(&get_type_def!(AstTransform)); output.push_str("\n\n");
        output.push_str(&get_type_def!(GraphNode)); output.push_str("\n\n");
        output.push_str(&get_type_def!(GraphEdge)); output.push_str("\n\n");
        output.push_str(&get_type_def!(AstGraph)); output.push_str("\n\n");
        output.push_str(&get_type_def!(AstCanvas)); output.push_str("\n\n");
        output.push_str(&get_type_def!(PropValue)); output.push_str("\n\n");
        output.push_str(&get_type_def!(AstShape)); output.push_str("\n\n");
        output.push_str(&get_type_def!(AstNode)); output.push_str("\n\n");
        output.push_str(&get_type_def!(ErrorSeverity)); output.push_str("\n\n");
        output.push_str(&get_type_def!(ErrorKind)); output.push_str("\n\n");
        output.push_str(&get_type_def!(Span)); output.push_str("\n\n");
        output.push_str(&get_type_def!(ParseError)); output.push_str("\n\n");

        output.push_str(r#"// ─────────────────────────────────────────────────────────────────────────────
// Scene Shape Types
// ─────────────────────────────────────────────────────────────────────────────

"#);
        output.push_str(&get_type_def!(Color)); output.push_str("\n\n");
        output.push_str(&get_type_def!(Style)); output.push_str("\n\n");
        output.push_str(&get_type_def!(Rect)); output.push_str("\n\n");
        output.push_str(&get_type_def!(Circle)); output.push_str("\n\n");
        output.push_str(&get_type_def!(Ellipse)); output.push_str("\n\n");
        output.push_str(&get_type_def!(Line)); output.push_str("\n\n");
        output.push_str(&get_type_def!(ShapePath)); output.push_str("\n\n");
        output.push_str(&get_type_def!(Polygon)); output.push_str("\n\n");
        output.push_str(&get_type_def!(Text)); output.push_str("\n\n");
        output.push_str(&get_type_def!(Image)); output.push_str("\n\n");
        output.push_str(&get_type_def!(Diamond)); output.push_str("\n\n");
        output.push_str(&get_type_def!(Node)); output.push_str("\n\n");
        output.push_str(&get_type_def!(EdgeStyle)); output.push_str("\n\n");
        output.push_str(&get_type_def!(ArrowType)); output.push_str("\n\n");
        output.push_str(&get_type_def!(Edge)); output.push_str("\n\n");

        output.push_str(r#"// ─────────────────────────────────────────────────────────────────────────────
// Scene Container Types
// ─────────────────────────────────────────────────────────────────────────────

"#);
        output.push_str(&get_type_def!(Element)); output.push_str("\n\n");
        output.push_str(&get_type_def!(GraphContainer)); output.push_str("\n\n");
        output.push_str(&get_type_def!(Gradient)); output.push_str("\n\n");
        output.push_str(&get_type_def!(Filter)); output.push_str("\n");
        
        let out_file = out_dir.join("types.ts");
        fs::write(&out_file, &output).expect("Failed to write TypeScript bindings");
        
        println!("\n✅ TypeScript bindings exported to: {}", out_file.display());
        println!("   {} bytes written", output.len());
    }
}
