/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const init: () => void;
export const size_to_pixels: (a: number, b: number) => any;
export const is_valid_size: (a: number, b: number) => number;
export const get_all_sizes: () => any;
export const get_size_info: (a: number, b: number) => any;
export const fnv1a_hash: (a: number, b: number) => [number, number];
export const compute_element_id: (a: number, b: number, c: number, d: any) => [number, number];
export const render_rect: (a: number, b: number, c: number, d: number, e: number, f: any, g: number, h: number) => [number, number];
export const render_circle: (a: number, b: number, c: number, d: any, e: number, f: number) => [number, number];
export const render_ellipse: (a: number, b: number, c: number, d: number, e: any, f: number, g: number) => [number, number];
export const render_line: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number];
export const render_path: (a: number, b: number, c: any, d: number, e: number) => [number, number];
export const render_polygon: (a: any, b: any, c: number, d: number) => [number, number];
export const render_text: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number) => [number, number];
export const measure_text: (a: number, b: number, c: number, d: number, e: number) => any;
export const compute_text_bounds: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => any;
export const render_image: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const render_linear_gradient: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const render_radial_gradient: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const render_shadow_filter: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const render_blur_filter: (a: number, b: number, c: number) => [number, number];
export const diff_scenes: (a: any, b: any) => any;
export const scenes_equal: (a: any, b: any) => number;
export const render_scene: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const compute_path_bounds: (a: number, b: number) => any;
export const render_diamond: (a: number, b: number, c: number, d: number, e: any, f: number, g: number) => [number, number];
export const render_node: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: any) => [number, number];
export const render_edge: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number) => [number, number];
export const render_arrow_markers: (a: number, b: number) => [number, number];
export const compute_edge_anchors: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => any;
export const layout_hierarchical: (a: any, b: number, c: number, d: number) => any;
export const layout_grid: (a: any, b: number) => any;
export const render_symbol: (a: number, b: number, c: number, d: number, e: any) => [number, number];
export const render_use: (a: number, b: number, c: number, d: number, e: any, f: any, g: any, h: number, i: number) => [number, number];
export const tokenize: (a: number, b: number) => [number, number];
export const parse: (a: number, b: number) => [number, number];
export const parse_with_errors: (a: number, b: number) => [number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
